#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
  path:     /api/login
  methods:  [POST]

check:
  path:     /api/token/check
  methods:  [GET]
  controller: App\Controller\CheckController::check

gesdinet_jwt_refresh_token:
  path:       /api/login/refresh
  controller: gesdinet.jwtrefreshtoken::refresh