#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
  path:     /api/login
  methods:  [POST]

gesdinet_jwt_refresh_token:
  path:       /api/login/refresh
  controller: gesdinet.jwtrefreshtoken::refresh